### ISSUE TITLE
Error in md2canvas: KeyError: 'ctype'

### ISSUE THREAD

**Issue by firasm** [maracieco/md2canvas#18]
Hello,

Current version of md2canvas seems to be failing. Running this command:

```
md2canvas -t 11224 <token> -c 45445 -u https://canvas.ubc.ca ~/Sync/Teaching/utilities/md2canvas/examples/sample_quiz/SampleQuiz.md
```

Here's the error message:
```
Parsing the quiz at /Users/firasm/Sync/Teaching/utilities/md2canvas/examples/sample_quiz/SampleQuiz.md
/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/jupytext/myst.py:76: UserWarning: myst-parse failed unexpectedly: default_parser() got an unexpected keyword argument 'disable_syntax'
  warnings.warn("myst-parse failed unexpectedly: {}".format(err))
Traceback (most recent call last):
  File "/Users/firasm/.pyenv/versions/3.8.3/bin/md2canvas", line 8, in <module>
    sys.exit(md2canvas())
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/command.py", line 100, in md2canvas
    quiz = m2j.parse_quiz(notebook_file)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/md2json.py", line 612, in parse_quiz
    if not start and cell["metadata"]["ctype"] == "quiz":
KeyError: 'ctype'
```

Let me know if you have any ideas... I wonder if this has something to do versions?

**Comment by maracieco** [comment]
This repo is being maintained at https://github.com/eoas-ubc/md2canvas now! Although I do have one idea for what could be causing this: incorrect myst-parser version or missing myst-parser package

**Comment by firasm** [comment]
ah ok - I think this is the same error as the failing pytest in #17 

Do you suggest moving this issue there? I'll try that repo first.

**Comment by maracieco** [comment]
Yeah, I'm not working on this project anymore! @phaustin should still be on it though

**Comment by firasm** [comment]
Ah okay. Thanks! 

@phaustin: it seems issues are not enabled in https://github.com/eoas-ubc/md2canvas - let me know if you can enable that and we can track it there.

**Comment by firasm** [comment]
Fixed the error by upgrading to the latest `jupytext. I had 1.5.1 but needed 1.6.0. (FYI 1.5.1 worked a few months ago).

**Comment by phaustin** [comment]
Hi @firasm -- fixed thanks.  I'll be using this for real in about a week, so definitely responding to issues.  @maracieco -- maybe archive this repo with a referring link on in the readme?
