### ISSUE TITLE
Configparser error

### ISSUE THREAD

**Issue by firasm** [maracieco/md2canvas#8]
I just tried running md2canvas, but I ran into an error:

The command I ran was:

```
md2canvas -t <RedactedCanvasToken> -c 45445 ~/Sync/Teaching/utilities/md2canvas/examples/sample_quiz/SampleQuiz.md
```
The error I got was:

```
Traceback (most recent call last):
  File "/Users/firasm/.pyenv/versions/3.8.3/bin/md2canvas", line 8, in <module>
    sys.exit(md2canvas())
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/command.py", line 84, in md2canvas
    url = config.get("settings", "url")
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'settings'
```

Haven't had a chance to debug this yet... let me know if you have any ideas.

**Comment by maracieco** [comment]
What OS are you on? I have only tested on Windows. 

You didn't provide the program a Canvas URL, so it tried to check the settings (md2canvas/config.ini) but didn't find a section called settings. I just tried cloning and running it fresh and didn't get this (even without supplying a URL).

**Comment by firasm** [comment]
I'm on macOS 10.15.6.

Ah, missing -u flag was my bad! New error now.

Relevant traceback:

```
Uploading quiz to Canvas with following settings:
  URL = https://canvas.ubc.ca/courses/45445
  Token = 1122**************************************************************cUgE
  Course ID = 45445
Traceback (most recent call last):
  File "/Users/firasm/.pyenv/versions/3.8.3/bin/md2canvas", line 8, in <module>
    sys.exit(md2canvas())
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/command.py", line 115, in md2canvas
    j2c.upload_quiz(quiz, url, token, course_id)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/json2canvas.py", line 197, in upload_quiz
    canvas_course = get_course(url, token, course_id)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/json2canvas.py", line 141, in get_course
    return canvas.get_course(course_id)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/canvasapi/canvas.py", line 638, in get_course
    response = self.__requester.request(
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/canvasapi/requester.py", line 242, in request
    raise ResourceDoesNotExist("Not Found")
canvasapi.exceptions.ResourceDoesNotExist: Not Found
```

Do I need to have the quiz created already in Canvas with the same name?


<details>
```
Parsing the quiz at /Users/firasm/Sync/Teaching/utilities/md2canvas/examples/sample_quiz/SampleQuiz.md
WARNING: File Upload questions do not work in preview mode.
WARNING: API does not support true/false questions, converting to multiple choice
{
    "attrs": {
        "description": "<h1>Test Canvas Quiz</h1>\n<p>A test quiz with all supported question types and some sample metadata.</p>\n<p>Part of <a href=\"https://github.com/hcolclou/md2canvas\">this github</a>.</p>\n<p>Here is a picture of a flower:</p>\n<p><img alt=\"flower image\" src=\"media/flower.jpg\" /></p>",
        "image_paths": [
            {
                "name": "media/flower.jpg",
                "path": "/Users/firasm/Sync/Teaching/utilities/md2canvas/examples/sample_quiz/media/flower.jpg"
            }
        ],
        "title": "Test Canvas Quiz",
        "allowed_attempts": 3,
        "scoring_policy": "keep_highest",
        "cant_go_back": false,
        "shuffle_answers": false
    },
    "groups": [
        {
            "attrs": {
                "name": "general"
            },
            "questions": [
                {
                    "question_name": "1",
                    "question_type": "essay_question",
                    "points_possible": 5,
                    "answers": [],
                    "question_text": "<h3>Question 1</h3>\n<p>Write your name here!</p>",
                    "image_paths": []
                },
                {
                    "question_name": "2",
                    "question_type": "file_upload_question",
                    "points_possible": 1,
                    "answers": [],
                    "question_text": "<h3>Question 2</h3>\n<p>Upload a file, any file (note this will not work in preview mode)!</p>",
                    "image_paths": []
                },
                {
                    "question_name": "3",
                    "question_type": "matching_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_match_left": "a",
                            "answer_match_right": "a"
                        },
                        {
                            "answer_match_left": "b",
                            "answer_match_right": "b"
                        },
                        {
                            "answer_match_left": "c",
                            "answer_match_right": "c"
                        },
                        {
                            "answer_match_left": "d",
                            "answer_match_right": "d"
                        }
                    ],
                    "question_text": "<h3>Question 3</h3>\n<p>Match the same letters to each other.</p>\n<p>Left</p>\n<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d</li>\n</ul>\n<p>Right</p>\n<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n<li>d</li>\n<li>e</li>\n<li>f</li>\n</ul>",
                    "matching_answer_incorrect_matches": "e\nf",
                    "image_paths": []
                },
                {
                    "question_name": "4",
                    "question_type": "multiple_answers_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_text": "1",
                            "answer_weight": 100
                        },
                        {
                            "answer_text": "2",
                            "answer_weight": 0
                        },
                        {
                            "answer_text": "3",
                            "answer_weight": 100
                        },
                        {
                            "answer_text": "4",
                            "answer_weight": 0
                        },
                        {
                            "answer_text": "5",
                            "answer_weight": 100
                        }
                    ],
                    "question_text": "<h3>Question 4</h3>\n<p>Choose the odd numbers.</p>\n<ul>\n<li>1</li>\n<li>2</li>\n<li>3</li>\n<li>4</li>\n<li>5</li>\n</ul>",
                    "image_paths": []
                },
                {
                    "question_name": "5",
                    "question_type": "multiple_choice_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_text": "Not this one",
                            "answer_weight": 0
                        },
                        {
                            "answer_text": "This one",
                            "answer_weight": 100
                        },
                        {
                            "answer_text": "Not this one either",
                            "answer_weight": 0
                        },
                        {
                            "answer_text": "All of the above",
                            "answer_weight": 0
                        }
                    ],
                    "question_text": "<h3>Question 5</h3>\n<p>What is the correct answer?</p>\n<ul>\n<li>Not this one</li>\n<li>This one</li>\n<li>Not this one either</li>\n<li>All of the above</li>\n</ul>",
                    "image_paths": []
                },
                {
                    "question_name": "6",
                    "question_type": "short_answer_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_text": "something"
                        },
                        {
                            "answer_text": "nothing"
                        }
                    ],
                    "question_text": "<h3>Question 6</h3>\n<p>Type \"something\" or \"nothing\".</p>",
                    "image_paths": []
                },
                {
                    "question_name": "7",
                    "question_type": "text_only_question",
                    "points_possible": 1,
                    "answers": [],
                    "question_text": "<h3>Question 7</h3>\n<p>Take a break!</p>",
                    "image_paths": []
                },
                {
                    "question_name": "8",
                    "question_type": "true_false_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_text": "True",
                            "answer_weight": 100
                        },
                        {
                            "answer_text": "False",
                            "answer_weight": 0
                        }
                    ],
                    "question_text": "<h3>Question 8</h3>\n<p>Write true to get full marks.</p>",
                    "image_paths": []
                }
            ]
        },
        {
            "attrs": {
                "name": "numerical questions",
                "pick_count": 1,
                "question_points": 3,
                "quesnum": 1
            },
            "questions": [
                {
                    "question_name": "9",
                    "question_type": "numerical_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 4.0,
                            "answer_error_margin": 0
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 4.0,
                            "answer_error_margin": 0.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 4.0,
                            "answer_error_margin": 0.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "range_answer",
                            "answer_range_start": 3.9,
                            "answer_range_end": 4.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "precision_answer",
                            "answer_approximate": 4.0,
                            "answer_precision": 2.0
                        }
                    ],
                    "question_text": "<h3>Question 9a</h3>\n<p>What is <img class=\"equation_image\" title=\"2 + 2\" src=\"/equation_images/2%2520%252B%25202\" alt=\"Latex: 2 + 2\" data-equation-content=\"2 + 2\" />?</p>",
                    "image_paths": []
                },
                {
                    "question_name": "10",
                    "question_type": "numerical_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 5.0,
                            "answer_error_margin": 0
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 5.0,
                            "answer_error_margin": 0.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 5.0,
                            "answer_error_margin": 0.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "range_answer",
                            "answer_range_start": 4.9,
                            "answer_range_end": 5.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "precision_answer",
                            "answer_approximate": 5.0,
                            "answer_precision": 2.0
                        }
                    ],
                    "question_text": "<h3>Question 9b</h3>\n<p>What is <img class=\"equation_image\" title=\"3 + 2\" src=\"/equation_images/3%2520%252B%25202\" alt=\"Latex: 3 + 2\" data-equation-content=\"3 + 2\" />?</p>",
                    "image_paths": []
                },
                {
                    "question_name": "11",
                    "question_type": "numerical_question",
                    "points_possible": 1,
                    "answers": [
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 6.0,
                            "answer_error_margin": 0
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 6.0,
                            "answer_error_margin": 0.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "exact_answer",
                            "answer_exact": 6.0,
                            "answer_error_margin": 0.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "range_answer",
                            "answer_range_start": 5.9,
                            "answer_range_end": 6.1
                        },
                        {
                            "answer_text": "",
                            "answer_weight": 100,
                            "numerical_answer_type": "precision_answer",
                            "answer_approximate": 6.0,
                            "answer_precision": 2.0
                        }
                    ],
                    "question_text": "<h3>Question 9c</h3>\n<p>Evaluate the following expression. </p><img class=\"equation_image\" title=\"4 + 2\" src=\"/equation_images/4%2520%252B%25202\" alt=\"Latex: 4 + 2\" data-equation-content=\"4 + 2\" /><p></p>",
                    "image_paths": []
                }
            ]
        }
    ]
}
Uploading quiz to Canvas with following settings:
  URL = https://canvas.ubc.ca/courses/45445
  Token = 1122**************************************************************cUgE
  Course ID = 45445
Traceback (most recent call last):
  File "/Users/firasm/.pyenv/versions/3.8.3/bin/md2canvas", line 8, in <module>
    sys.exit(md2canvas())
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/command.py", line 115, in md2canvas
    j2c.upload_quiz(quiz, url, token, course_id)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/json2canvas.py", line 197, in upload_quiz
    canvas_course = get_course(url, token, course_id)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/md2canvas/json2canvas.py", line 141, in get_course
    return canvas.get_course(course_id)
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/canvasapi/canvas.py", line 638, in get_course
    response = self.__requester.request(
  File "/Users/firasm/.pyenv/versions/3.8.3/lib/python3.8/site-packages/canvasapi/requester.py", line 242, in request
    raise ResourceDoesNotExist("Not Found")
canvasapi.exceptions.ResourceDoesNotExist: Not Found
```

</details>

**Comment by maracieco** [comment]
It should be able to create an entirely new quiz. It will only attempt to update an existing quiz if you give it a quiz ID. It looks like it failed to get the course, are you sure that the course ID you used is correct?

**Comment by firasm** [comment]
Hmm - yea, looks correct to me (screenshot below): 45445

![Screen Shot 2020-08-06 at 6 32 05 PM](https://user-images.githubusercontent.com/2507459/89599015-2e3dc600-d813-11ea-8cc1-4fd556be87cb.png)

**Comment by maracieco** [comment]
Oops I missed it in your previous comment, the URL shouldn't include the course, just https://canvas.ubc.ca

**Comment by firasm** [comment]
aha! That worked!! 

Thank you, I will update my instructions in #9
